export type Language = 'English' | 'Hindi' | 'Bengali';

export const TRANSLATIONS = {
  English: {
    title: "Future Classroom Simulator",
    subtitle: "Trainee Teacher Interactive Simulator",
    setupTitle: "New Lesson Simulation Setup",
    historyTitle: "Training Session History",
    noHistory: "No prior training sessions found. Start a new one above!",
    subject: "Subject",
    subjectPlaceholder: "e.g., Physics, History, English",
    topic: "Lesson Topic",
    topicPlaceholder: "e.g., Law of Gravity, French Revolution",
    classLevel: "Class Grade Level",
    primary: "Primary (Grades 1-5)",
    middle: "Middle School (Grades 6-8)",
    high: "High School (Grades 9-12)",
    objectives: "Lesson Objectives & Outcomes",
    objectivesPlaceholder: "What should students achieve by the end of this lesson?",
    method: "Primary Teaching Method",
    methodLecture: "Direct Lecture (Explanation-heavy)",
    methodDiscussion: "Socratic Discussion (Interactive)",
    methodQA: "Q&A & Probing Questions",
    methodInquiry: "Inquiry-based Learning",
    duration: "Simulation Duration",
    durationVal: "{val} Minutes",
    language: "Classroom Language",
    startBtn: "Initialize Virtual Classroom",
    backBtn: "Exit to Dashboard",
    endBtn: "End Session & Run Assessment",
    micListening: "Listening...",
    micIdle: "Click Mic to Speak",
    typePlaceholder: "Type your explanation, question, or response here...",
    classroomStatus: "Live Classroom Session",
    timeLeft: "Time Remaining",
    minutes: "m",
    seconds: "s",
    recentTranscript: "Dialogue Transcript Log",
    evaluationTitle: "Pedagogical Performance Assessment",
    scoreCommunication: "Communication & Clarity",
    scoreEngagement: "Student Engagement",
    scoreTime: "Time Management",
    scoreQuestion: "Question Handling",
    overallScore: "Teaching Score",
    suggestionsTitle: "Evaluator Suggestions & Actionable Feedback",
    transcriptSummaryTitle: "Session Summary",
    retryBtn: "Simulate New Session",
    studentsHeader: "Virtual Student Group",
    callingOn: "Addressing {name}...",
    refocusAction: "Reminded {name} to focus.",
    wakeAction: "Prompted {name} to participate.",
    explainAction: "Scaffolded topic simply for {name}.",
    systemTitle: "Classroom Notification",
    systemEventAlert: "Event Triggered"
  },
  Hindi: {
    title: "फ्यूचर क्लासरूम सिम्युलेटर",
    subtitle: "प्रशिक्षण शिक्षक इंटरएक्टिव सिम्युलेटर",
    setupTitle: "नया पाठ सिमुलेशन सेटअप",
    historyTitle: "प्रशिक्षण सत्र का इतिहास",
    noHistory: "कोई पिछला सत्र नहीं मिला। ऊपर से एक नया सत्र शुरू करें!",
    subject: "विषय",
    subjectPlaceholder: "जैसे, भौतिकी, इतिहास, अंग्रेजी",
    topic: "पाठ का विषय",
    topicPlaceholder: "जैसे, गुरुत्वाकर्षण का नियम, फ्रांसीसी क्रांति",
    classLevel: "कक्षा का स्तर",
    primary: "प्राथमिक (कक्षा 1-5)",
    middle: "मिडिल स्कूल (कक्षा 6-8)",
    high: "हाई स्कूल (कक्षा 9-12)",
    objectives: "पाठ के उद्देश्य और परिणाम",
    objectivesPlaceholder: "इस पाठ के अंत तक छात्रों को क्या हासिल करना चाहिए?",
    method: "मुख्य शिक्षण पद्धति",
    methodLecture: "व्याख्यान विधि (शिक्षक-केंद्रित)",
    methodDiscussion: "सॉक्रेटिक चर्चा (संवादात्मक)",
    methodQA: "प्रश्न-उत्तर और जांच प्रश्न",
    methodInquiry: "पूछताछ आधारित शिक्षा",
    duration: "सिमुलेशन की अवधि",
    durationVal: "{val} मिनट",
    language: "कक्षा की भाषा",
    startBtn: "वर्चुअल क्लासरूम शुरू करें",
    backBtn: "डैशबोर्ड पर वापस जाएं",
    endBtn: "सत्र समाप्त करें और मूल्यांकन करें",
    micListening: "सुन रहा है...",
    micIdle: "बोलने के लिए माइक दबाएं",
    typePlaceholder: "अपना स्पष्टीकरण, प्रश्न या उत्तर यहाँ टाइप करें...",
    classroomStatus: "सक्रिय क्लासरूम सत्र",
    timeLeft: "शेष समय",
    minutes: "मिनट",
    seconds: "सेकंड",
    recentTranscript: "संवाद प्रतिलेख (ट्रांसक्रिप्ट)",
    evaluationTitle: "शैक्षणिक प्रदर्शन मूल्यांकन",
    scoreCommunication: "संचार और स्पष्टता",
    scoreEngagement: "छात्र सहभागिता",
    scoreTime: "समय प्रबंधन",
    scoreQuestion: "प्रश्न संचालन",
    overallScore: "शिक्षण स्कोर",
    suggestionsTitle: "मूल्यांकनकर्ता के सुझाव और फीडबैक",
    transcriptSummaryTitle: "सत्र का सारांश",
    retryBtn: "नया सत्र शुरू करें",
    studentsHeader: "वर्चुअल छात्र समूह",
    callingOn: "{name} को संबोधित कर रहे हैं...",
    refocusAction: "{name} को ध्यान केंद्रित करने को कहा।",
    wakeAction: "{name} को भाग लेने के लिए प्रेरित किया।",
    explainAction: "{name} के लिए विषय को सरल बनाया।",
    systemTitle: "क्लासरूम सूचना",
    systemEventAlert: "घटना घटित हुई"
  },
  Bengali: {
    title: "ফিউচার ক্লাসরুম সিমুলেটর",
    subtitle: "প্রশিক্ষণার্থী শিক্ষক ইন্টারঅ্যাক্টিভ সিমুলেটর",
    setupTitle: "নতুন পাঠ সিমুলেশন সেটআপ",
    historyTitle: "প্রশিক্ষণ সেশনের ইতিহাস",
    noHistory: "কোনো পূর্ববর্তী সেশন পাওয়া যায়নি। উপরে একটি নতুন সেশন শুরু করুন!",
    subject: "বিষয়",
    subjectPlaceholder: "উদাঃ পদার্থবিজ্ঞান, ইতিহাস, ইংরেজি",
    topic: "পাঠের বিষয়বস্তু",
    topicPlaceholder: "উদাঃ অভিকর্ষ সূত্র, ফরাসি বিপ্লব",
    classLevel: "শ্রেণীর স্তর",
    primary: "প্রাথমিক (শ্রেণী ১-৫)",
    middle: "মিডল স্কুল (শ্রেণী ৬-৮)",
    high: "হাই স্কুল (শ্রেণী ৯-১২)",
    objectives: "পাঠের উদ্দেশ্য ও শিখনফল",
    objectivesPlaceholder: "এই পাঠের শেষে শিক্ষার্থীরা কী শিখতে পারবে?",
    method: "প্রধান শিক্ষাদান পদ্ধতি",
    methodLecture: "বক্তৃতা পদ্ধতি (ব্যাখ্যামূলক)",
    methodDiscussion: "সক্রেটিক আলোচনা (পারস্পরিক)",
    methodQA: "প্রশ্নোত্তর ও অনুসন্ধানমূলক প্রশ্ন",
    methodInquiry: "অনুসন্ধান-ভিত্তিক শিক্ষা",
    duration: "সিমুলেশন সময়সীমা",
    durationVal: "{val} মিনিট",
    language: "শ্রেণীকক্ষের ভাষা",
    startBtn: "ভার্চুয়াল ক্লাসরুম শুরু করুন",
    backBtn: "ড্যাশবোর্ডে ফিরে যান",
    endBtn: "সেশন সমাপ্ত ও মূল্যায়ন করুন",
    micListening: "শুনছে...",
    micIdle: "বলার জন্য মাইক টিপুন",
    typePlaceholder: "আপনার ব্যাখ্যা, প্রশ্ন বা উত্তর এখানে লিখুন...",
    classroomStatus: "লাইভ শ্রেণীকক্ষ সেশন",
    timeLeft: "অবশিষ্ট সময়",
    minutes: "মিঃ",
    seconds: "সেঃ",
    recentTranscript: "কথোপকথনের বিবরণী (ট্রান্সক্রিপ্ট)",
    evaluationTitle: "শিক্ষণ কর্মক্ষমতা মূল্যায়ন",
    scoreCommunication: "যোগাযোগ ও স্পষ্টতা",
    scoreEngagement: "শিক্ষার্থী অংশগ্রহণ",
    scoreTime: "সময় ব্যবস্থাপনা",
    scoreQuestion: "প্রশ্নোত্তর পরিচালনা",
    overallScore: "শিক্ষণ স্কোর",
    suggestionsTitle: "পরীক্ষকের পরামর্শ ও ফিডব্যাক",
    transcriptSummaryTitle: "সেশনের সংক্ষিপ্তসার",
    retryBtn: "নতুন সেশন শুরু করুন",
    studentsHeader: "ভার্চুয়াল ছাত্র দল",
    callingOn: "{name}-কে সম্বোধন করা হচ্ছে...",
    refocusAction: "{name}-কে মনোযোগী হতে বলা হলো।",
    wakeAction: "{name}-কে অংশগ্রহণ করতে বলা হলো।",
    explainAction: "{name}-এর জন্য বিষয়টিকে সহজ করা হলো।",
    systemTitle: "শ্রেণীকক্ষ বিজ্ঞপ্তি",
    systemEventAlert: "ঘটনা ঘটেছে"
  }
};
